version: '{build}'
skip_tags: true

install:
    - cinst jdk10 -params 'installdir=C:\\jdk10'

build_script:
    - gradlew.bat assemble

test_script:
    - gradlew.bat check

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
        - JAVA_HOME: C:\jdk10

matrix:
    fast_finish: true
