version: '{build}'
skip_tags: true
skip_branch_with_pr: true

build_script:
    - gradlew.bat assemble

test_script:
    - gradlew.bat check

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
    fast_finish: true
