language: java
sudo: required
dist: trusty
group: edge
addons:
  sonarcloud:
    organization: trellis-ldp

matrix:
  fast_finish: true
  include:
  - jdk: oraclejdk8
    after_success: "./gradlew jacocoRootReport coveralls sonarqube"
  - jdk: oraclejdk9
  - jdk: oraclejdk10
  - jdk: oraclejdk11

script: "./gradlew clean check install"
