language: java
sudo: false
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - main
    # release tags
    - /^camel-ldp-recipes-\d+\.\d+\.\d+$/
    # maintenance branches
    - /^camel-ldp-recipes-\d+\.\d+\.x$/
    # long-lived branches
    - /branch-.+/

stages:
  - test
  - deploy

env:
    - JOB=check

jobs:
    fast_finish: true

    allow_failures:
      - env: JOB=sonatype

    include:
        # JDK 11
        - name: "Java 11"
          stage: test
          jdk: openjdk11
          dist: xenial
          script: ./gradlew check install jacocoRootReport
          after_success: ./gradlew coveralls sonarqube

        - name: "Publish to Sonatype"
          stage: deploy
          jdk: openjdk11
          env: JOB=sonatype
          if: branch = main AND type = push
          # Only automate the publication of SNAPSHOTS
          script: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew publish ; fi
